//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Compteur complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Compteur">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Matricule_Compteur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Nombre_Cadrans">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Periode" type="{}Periode" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Compteur", propOrder = {
    "matriculeCompteur",
    "nombreCadrans",
    "periode"
})
public class Compteur {

    @XmlElement(name = "Matricule_Compteur", required = true)
    protected String matriculeCompteur;
    @XmlElement(name = "Nombre_Cadrans", required = true)
    protected BigInteger nombreCadrans;
    @XmlElement(name = "Periode", required = true)
    protected List<Periode> periode;

    /**
     * Gets the value of the matriculeCompteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatriculeCompteur() {
        return matriculeCompteur;
    }

    /**
     * Sets the value of the matriculeCompteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatriculeCompteur(String value) {
        this.matriculeCompteur = value;
    }

    /**
     * Gets the value of the nombreCadrans property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNombreCadrans() {
        return nombreCadrans;
    }

    /**
     * Sets the value of the nombreCadrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNombreCadrans(BigInteger value) {
        this.nombreCadrans = value;
    }

    /**
     * Gets the value of the periode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Periode }
     * 
     * 
     */
    public List<Periode> getPeriode() {
        if (periode == null) {
            periode = new ArrayList<Periode>();
        }
        return this.periode;
    }

}
