//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Coordonnees_Destinataire complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Coordonnees_Destinataire">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Coordonnees_D_Ligne1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne6" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_D_Ligne7" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="38"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Coordonnees_Destinataire", propOrder = {
    "coordonneesDLigne1",
    "coordonneesDLigne2",
    "coordonneesDLigne3",
    "coordonneesDLigne4",
    "coordonneesDLigne5",
    "coordonneesDLigne6",
    "coordonneesDLigne7"
})
public class CoordonneesDestinataire {

    @XmlElement(name = "Coordonnees_D_Ligne1", required = true)
    protected String coordonneesDLigne1;
    @XmlElement(name = "Coordonnees_D_Ligne2")
    protected String coordonneesDLigne2;
    @XmlElement(name = "Coordonnees_D_Ligne3")
    protected String coordonneesDLigne3;
    @XmlElement(name = "Coordonnees_D_Ligne4")
    protected String coordonneesDLigne4;
    @XmlElement(name = "Coordonnees_D_Ligne5")
    protected String coordonneesDLigne5;
    @XmlElement(name = "Coordonnees_D_Ligne6")
    protected String coordonneesDLigne6;
    @XmlElement(name = "Coordonnees_D_Ligne7")
    protected String coordonneesDLigne7;

    /**
     * Gets the value of the coordonneesDLigne1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne1() {
        return coordonneesDLigne1;
    }

    /**
     * Sets the value of the coordonneesDLigne1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne1(String value) {
        this.coordonneesDLigne1 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne2() {
        return coordonneesDLigne2;
    }

    /**
     * Sets the value of the coordonneesDLigne2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne2(String value) {
        this.coordonneesDLigne2 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne3() {
        return coordonneesDLigne3;
    }

    /**
     * Sets the value of the coordonneesDLigne3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne3(String value) {
        this.coordonneesDLigne3 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne4() {
        return coordonneesDLigne4;
    }

    /**
     * Sets the value of the coordonneesDLigne4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne4(String value) {
        this.coordonneesDLigne4 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne5() {
        return coordonneesDLigne5;
    }

    /**
     * Sets the value of the coordonneesDLigne5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne5(String value) {
        this.coordonneesDLigne5 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne6() {
        return coordonneesDLigne6;
    }

    /**
     * Sets the value of the coordonneesDLigne6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne6(String value) {
        this.coordonneesDLigne6 = value;
    }

    /**
     * Gets the value of the coordonneesDLigne7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordonneesDLigne7() {
        return coordonneesDLigne7;
    }

    /**
     * Sets the value of the coordonneesDLigne7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordonneesDLigne7(String value) {
        this.coordonneesDLigne7 = value;
    }

}
