//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Donnees_Cadran complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Donnees_Cadran">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rang_Cadran">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Nature_Index_Debut" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Processus_Index_Debut" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Index_Debut_Consommation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;totalDigits value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Origine_Index_Debut" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Indicateur_Passage_A_Zero" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Nature_Index_A_Facturer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Processus_Index_A_Facturer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Index_A_Facturer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;totalDigits value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Origine_Index_A_Facturer" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Consommation_Cadran" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Donnees_Cadran", propOrder = {
    "rangCadran",
    "natureIndexDebut",
    "processusIndexDebut",
    "indexDebutConsommation",
    "origineIndexDebut",
    "indicateurPassageAZero",
    "natureIndexAFacturer",
    "processusIndexAFacturer",
    "indexAFacturer",
    "origineIndexAFacturer",
    "consommationCadran"
})
public class DonneesCadran {

    @XmlElement(name = "Rang_Cadran", required = true)
    protected String rangCadran;
    @XmlElement(name = "Nature_Index_Debut")
    protected String natureIndexDebut;
    @XmlElement(name = "Processus_Index_Debut")
    protected String processusIndexDebut;
    @XmlElement(name = "Index_Debut_Consommation")
    protected BigInteger indexDebutConsommation;
    @XmlElement(name = "Origine_Index_Debut")
    protected String origineIndexDebut;
    @XmlElement(name = "Indicateur_Passage_A_Zero")
    protected String indicateurPassageAZero;
    @XmlElement(name = "Nature_Index_A_Facturer")
    protected String natureIndexAFacturer;
    @XmlElement(name = "Processus_Index_A_Facturer")
    protected String processusIndexAFacturer;
    @XmlElement(name = "Index_A_Facturer")
    protected BigInteger indexAFacturer;
    @XmlElement(name = "Origine_Index_A_Facturer")
    protected String origineIndexAFacturer;
    @XmlElement(name = "Consommation_Cadran")
    protected Integer consommationCadran;

    /**
     * Gets the value of the rangCadran property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangCadran() {
        return rangCadran;
    }

    /**
     * Sets the value of the rangCadran property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangCadran(String value) {
        this.rangCadran = value;
    }

    /**
     * Gets the value of the natureIndexDebut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureIndexDebut() {
        return natureIndexDebut;
    }

    /**
     * Sets the value of the natureIndexDebut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureIndexDebut(String value) {
        this.natureIndexDebut = value;
    }

    /**
     * Gets the value of the processusIndexDebut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessusIndexDebut() {
        return processusIndexDebut;
    }

    /**
     * Sets the value of the processusIndexDebut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessusIndexDebut(String value) {
        this.processusIndexDebut = value;
    }

    /**
     * Gets the value of the indexDebutConsommation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndexDebutConsommation() {
        return indexDebutConsommation;
    }

    /**
     * Sets the value of the indexDebutConsommation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndexDebutConsommation(BigInteger value) {
        this.indexDebutConsommation = value;
    }

    /**
     * Gets the value of the origineIndexDebut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigineIndexDebut() {
        return origineIndexDebut;
    }

    /**
     * Sets the value of the origineIndexDebut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigineIndexDebut(String value) {
        this.origineIndexDebut = value;
    }

    /**
     * Gets the value of the indicateurPassageAZero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicateurPassageAZero() {
        return indicateurPassageAZero;
    }

    /**
     * Sets the value of the indicateurPassageAZero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicateurPassageAZero(String value) {
        this.indicateurPassageAZero = value;
    }

    /**
     * Gets the value of the natureIndexAFacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureIndexAFacturer() {
        return natureIndexAFacturer;
    }

    /**
     * Sets the value of the natureIndexAFacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureIndexAFacturer(String value) {
        this.natureIndexAFacturer = value;
    }

    /**
     * Gets the value of the processusIndexAFacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessusIndexAFacturer() {
        return processusIndexAFacturer;
    }

    /**
     * Sets the value of the processusIndexAFacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessusIndexAFacturer(String value) {
        this.processusIndexAFacturer = value;
    }

    /**
     * Gets the value of the indexAFacturer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndexAFacturer() {
        return indexAFacturer;
    }

    /**
     * Sets the value of the indexAFacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndexAFacturer(BigInteger value) {
        this.indexAFacturer = value;
    }

    /**
     * Gets the value of the origineIndexAFacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigineIndexAFacturer() {
        return origineIndexAFacturer;
    }

    /**
     * Sets the value of the origineIndexAFacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigineIndexAFacturer(String value) {
        this.origineIndexAFacturer = value;
    }

    /**
     * Gets the value of the consommationCadran property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getConsommationCadran() {
        return consommationCadran;
    }

    /**
     * Sets the value of the consommationCadran property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setConsommationCadran(Integer value) {
        this.consommationCadran = value;
    }

}
