//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Entete complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entete">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifiant_Flux">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Libelle_Flux">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Identifiant_Emetteur">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_Emetteur" type="{}Coordonnees_Emetteur"/>
 *         &lt;element name="Identifiant_Destinataire">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Coordonnees_Destinataire" type="{}Coordonnees_Destinataire"/>
 *         &lt;element name="Date_Version_Message" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Date_Creation" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entete", propOrder = {
    "identifiantFlux",
    "libelleFlux",
    "identifiantEmetteur",
    "coordonneesEmetteur",
    "identifiantDestinataire",
    "coordonneesDestinataire",
    "dateVersionMessage",
    "dateCreation"
})
public class Entete {

    @XmlElement(name = "Identifiant_Flux", required = true)
    protected String identifiantFlux;
    @XmlElement(name = "Libelle_Flux", required = true)
    protected String libelleFlux;
    @XmlElement(name = "Identifiant_Emetteur", required = true)
    protected String identifiantEmetteur;
    @XmlElement(name = "Coordonnees_Emetteur", required = true)
    protected CoordonneesEmetteur coordonneesEmetteur;
    @XmlElement(name = "Identifiant_Destinataire", required = true)
    protected String identifiantDestinataire;
    @XmlElement(name = "Coordonnees_Destinataire", required = true)
    protected CoordonneesDestinataire coordonneesDestinataire;
    @XmlElement(name = "Date_Version_Message")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateVersionMessage;
    @XmlElement(name = "Date_Creation", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreation;

    /**
     * Gets the value of the identifiantFlux property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifiantFlux() {
        return identifiantFlux;
    }

    /**
     * Sets the value of the identifiantFlux property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifiantFlux(String value) {
        this.identifiantFlux = value;
    }

    /**
     * Gets the value of the libelleFlux property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibelleFlux() {
        return libelleFlux;
    }

    /**
     * Sets the value of the libelleFlux property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibelleFlux(String value) {
        this.libelleFlux = value;
    }

    /**
     * Gets the value of the identifiantEmetteur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifiantEmetteur() {
        return identifiantEmetteur;
    }

    /**
     * Sets the value of the identifiantEmetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifiantEmetteur(String value) {
        this.identifiantEmetteur = value;
    }

    /**
     * Gets the value of the coordonneesEmetteur property.
     * 
     * @return
     *     possible object is
     *     {@link CoordonneesEmetteur }
     *     
     */
    public CoordonneesEmetteur getCoordonneesEmetteur() {
        return coordonneesEmetteur;
    }

    /**
     * Sets the value of the coordonneesEmetteur property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordonneesEmetteur }
     *     
     */
    public void setCoordonneesEmetteur(CoordonneesEmetteur value) {
        this.coordonneesEmetteur = value;
    }

    /**
     * Gets the value of the identifiantDestinataire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifiantDestinataire() {
        return identifiantDestinataire;
    }

    /**
     * Sets the value of the identifiantDestinataire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifiantDestinataire(String value) {
        this.identifiantDestinataire = value;
    }

    /**
     * Gets the value of the coordonneesDestinataire property.
     * 
     * @return
     *     possible object is
     *     {@link CoordonneesDestinataire }
     *     
     */
    public CoordonneesDestinataire getCoordonneesDestinataire() {
        return coordonneesDestinataire;
    }

    /**
     * Sets the value of the coordonneesDestinataire property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordonneesDestinataire }
     *     
     */
    public void setCoordonneesDestinataire(CoordonneesDestinataire value) {
        this.coordonneesDestinataire = value;
    }

    /**
     * Gets the value of the dateVersionMessage property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateVersionMessage() {
        return dateVersionMessage;
    }

    /**
     * Sets the value of the dateVersionMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateVersionMessage(XMLGregorianCalendar value) {
        this.dateVersionMessage = value;
    }

    /**
     * Gets the value of the dateCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the value of the dateCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreation(XMLGregorianCalendar value) {
        this.dateCreation = value;
    }

}
