//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Index_C5 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Index_C5">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Entete" type="{}Entete"/>
 *         &lt;element name="Corps_de_fichier_par_PDL" type="{}Corps_de_fichier_par_PDL" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Index_C5", propOrder = {
    "entete",
    "corpsDeFichierParPDL"
})
public class IndexC5 {

    @XmlElement(name = "Entete", required = true)
    protected Entete entete;
    @XmlElement(name = "Corps_de_fichier_par_PDL", required = true)
    protected List<CorpsDeFichierParPDL> corpsDeFichierParPDL;

    /**
     * Gets the value of the entete property.
     * 
     * @return
     *     possible object is
     *     {@link Entete }
     *     
     */
    public Entete getEntete() {
        return entete;
    }

    /**
     * Sets the value of the entete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entete }
     *     
     */
    public void setEntete(Entete value) {
        this.entete = value;
    }

    /**
     * Gets the value of the corpsDeFichierParPDL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the corpsDeFichierParPDL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorpsDeFichierParPDL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CorpsDeFichierParPDL }
     * 
     * 
     */
    public List<CorpsDeFichierParPDL> getCorpsDeFichierParPDL() {
        if (corpsDeFichierParPDL == null) {
            corpsDeFichierParPDL = new ArrayList<CorpsDeFichierParPDL>();
        }
        return this.corpsDeFichierParPDL;
    }

}
