//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the demo.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IndexC5_QNAME = new QName("", "Index_C5");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: demo.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoordonneesDestinataire }
     * 
     */
    public CoordonneesDestinataire createCoordonneesDestinataire() {
        return new CoordonneesDestinataire();
    }

    /**
     * Create an instance of {@link Periode }
     * 
     */
    public Periode createPeriode() {
        return new Periode();
    }

    /**
     * Create an instance of {@link Compteur }
     * 
     */
    public Compteur createCompteur() {
        return new Compteur();
    }

    /**
     * Create an instance of {@link Entete }
     * 
     */
    public Entete createEntete() {
        return new Entete();
    }

    /**
     * Create an instance of {@link SituationContrat }
     * 
     */
    public SituationContrat createSituationContrat() {
        return new SituationContrat();
    }

    /**
     * Create an instance of {@link CoordonneesEmetteur }
     * 
     */
    public CoordonneesEmetteur createCoordonneesEmetteur() {
        return new CoordonneesEmetteur();
    }

    /**
     * Create an instance of {@link IndexC5 }
     * 
     */
    public IndexC5 createIndexC5() {
        return new IndexC5();
    }

    /**
     * Create an instance of {@link DonneesCadran }
     * 
     */
    public DonneesCadran createDonneesCadran() {
        return new DonneesCadran();
    }

    /**
     * Create an instance of {@link CorpsDeFichierParPDL }
     * 
     */
    public CorpsDeFichierParPDL createCorpsDeFichierParPDL() {
        return new CorpsDeFichierParPDL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexC5 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Index_C5")
    public JAXBElement<IndexC5> createIndexC5(IndexC5 value) {
        return new JAXBElement<IndexC5>(_IndexC5_QNAME, IndexC5 .class, null, value);
    }

}
