//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 05:33:55 PM CEST 
//


package demo.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Periode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Periode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Indicateur_De_Periode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Puissance_Souscrite">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Donnees_Cadran" type="{}Donnees_Cadran" maxOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Periode", propOrder = {
    "indicateurDePeriode",
    "puissanceSouscrite",
    "donneesCadran"
})
public class Periode {

    @XmlElement(name = "Indicateur_De_Periode", required = true)
    protected String indicateurDePeriode;
    @XmlElement(name = "Puissance_Souscrite", required = true)
    protected BigInteger puissanceSouscrite;
    @XmlElement(name = "Donnees_Cadran", required = true)
    protected List<DonneesCadran> donneesCadran;

    /**
     * Gets the value of the indicateurDePeriode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicateurDePeriode() {
        return indicateurDePeriode;
    }

    /**
     * Sets the value of the indicateurDePeriode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicateurDePeriode(String value) {
        this.indicateurDePeriode = value;
    }

    /**
     * Gets the value of the puissanceSouscrite property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPuissanceSouscrite() {
        return puissanceSouscrite;
    }

    /**
     * Sets the value of the puissanceSouscrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPuissanceSouscrite(BigInteger value) {
        this.puissanceSouscrite = value;
    }

    /**
     * Gets the value of the donneesCadran property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the donneesCadran property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDonneesCadran().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DonneesCadran }
     * 
     * 
     */
    public List<DonneesCadran> getDonneesCadran() {
        if (donneesCadran == null) {
            donneesCadran = new ArrayList<DonneesCadran>();
        }
        return this.donneesCadran;
    }

}
